DROP TABLE MEMBER;

CREATE TABLE MEMBER(
ID VARCHAR(100) NOT NULL, /* 아이디 */ 
PASSWORD VARCHAR(100) NOT NULL, /* 비밀번호 */
NAME VARCHAR(50) NOT NULL, /* 이름 */
BIRTH VARCHAR(20) NOT NULL, /* 생년월일 */ 
TEL VARCHAR(100) NOT NULL, /* 연락처 */
ZIPCODE VARCHAR(255) NULL, /* 우편번호 */
USER_TYPE VARCHAR(10) NULL, 
ADDRESS VARCHAR(255) NULL,
DEL_YN VARCHAR(10) NULL,
REG_DT DATE NOT NULL,
MOD_DT DATE NOT NULL
);

ALTER TABLE MEMBER
ADD CONSTRAINT PK_MEMBER PRIMARY KEY(ID);


INSERT INTO MEMBER VALUES('admin','YgCD8w3LJSMx3uoomEDN0w==','관리자','1991-11-15','010-4457-9876',NULL,NULL,'A','N',SYSDATE,SYSDATE);